/**
 * DetailFieldControl — the runtime form-field renderer: resolves the
 * field's control plugin, wires validation (metadata rules + layout block
 * rules), and renders label/input/display for the detail page.
 */
import React from 'react';
import type { SailsFieldDefinition } from '@sails/shared';
import { validateFieldValue, isEmptyValue } from '@sails/shared';
import { FieldControlRegistry } from './FieldControlRegistry';
import { ControlLazyBoundary } from './LazyRenderErrorBoundary';
import type { FieldValidation, ConditionOp } from './types';

// ── Shared control resolution ──────────────────────────────────
// Single source of truth for resolving a field to its control plugin.
// Used by both the real Detail View page and the Layout Studio canvas
// so previews render exactly like the front-end.

export function resolveControlPlugin(field: SailsFieldDefinition, controlPluginId?: string) {
  const controlRegistry = FieldControlRegistry.getInstance();
  const logicalType = field.logicalType || field.physicalType || 'text';
  const configStyle = (field?.config as any)?.controlStyle;
  // Legacy field-level Display Control values map onto registered control ids.
  const styleToControlId: Record<string, string> = {
    search_list: 'control:relation_search_list',
  };
  const effectiveControlId = controlPluginId || (field?.config as any)?.defaultControl || (styleToControlId[configStyle] || configStyle);
  const controlPlugin = (effectiveControlId ? controlRegistry.getControl(effectiveControlId) : null) || controlRegistry.getFallbackControl(logicalType);
  return { controlPlugin, logicalType, effectiveControlId };
}

// Realistic sample value for designer previews, delegated to each
// control plugin (falls back to a generic sample string).
export function mockFieldValue(field: SailsFieldDefinition, controlPluginId?: string): any {
  const { controlPlugin } = resolveControlPlugin(field, controlPluginId);
  if (controlPlugin.mockValue) return controlPlugin.mockValue(field);
  return `Sample ${field.name}`;
}

// ── Field label (exact front-end markup) ───────────────────────

export function DetailFieldLabel({ field, label }: { field: SailsFieldDefinition; label?: string }) {
  return (
    <label className="ls-block__label">
      {label || field.name}
      {field.isRequired && <span className="ls-block__required">*</span>}
    </label>
  );
}

// ── On-Edit control (exact front-end wrapper markup) ───────────

// ── Block-level rule evaluation ─────────────────────────────────
// Layout Studio lets authors attach validation rules per field block
// (required / regex / range / cross_field). These run client-side in
// the real detail form and the Studio preview (WYSIWYG). The server
// enforces field-config rules (isRequired, min/max, maxLength) via the
// shared validator in @sails/shared — block rules live only in layout
// config, which the core API does not load.

function compareCondition(op: ConditionOp | undefined, a: any, b: any): boolean {
  switch (op) {
    case 'eq': return String(a ?? '') === String(b ?? '');
    case 'neq': return String(a ?? '') !== String(b ?? '');
    case 'gt': return Number(a) > Number(b);
    case 'gte': return Number(a) >= Number(b);
    case 'lt': return Number(a) < Number(b);
    case 'lte': return Number(a) <= Number(b);
    case 'contains': return String(a ?? '').toLowerCase().includes(String(b ?? '').toLowerCase());
    case 'empty': return a === undefined || a === null || String(a).trim() === '';
    case 'not_empty': return a !== undefined && a !== null && String(a).trim() !== '';
    default: return true;
  }
}

function evaluateBlockRules(
  rules: FieldValidation[] | undefined,
  val: any,
  record: Record<string, any> | undefined,
  isAutoNumber = false
): string[] {
  if (!rules || rules.length === 0) return [];
  const issues: string[] = [];

  for (const rule of rules) {
    switch (rule.type) {
      case 'required':
        // Auto-number values are generated by the DB on insert — never required-validate them.
        if (!isAutoNumber && isEmptyValue(val)) issues.push(rule.message || 'This field is required');
        break;

      case 'regex': {
        if (!isEmptyValue(val) && rule.pattern) {
          try {
            if (!new RegExp(rule.pattern).test(String(val))) {
              issues.push(rule.message || 'Value does not match the required format');
            }
          } catch {
            // invalid pattern — ignore
          }
        }
        break;
      }

      case 'range': {
        if (!isEmptyValue(val)) {
          const n = Number(val);
          if (!Number.isNaN(n)) {
            if (rule.min !== undefined && rule.min !== null && n < rule.min) {
              issues.push(rule.message || `Must be at least ${rule.min}`);
            }
            if (rule.max !== undefined && rule.max !== null && n > rule.max) {
              issues.push(rule.message || `Must be at most ${rule.max}`);
            }
          }
        }
        break;
      }

      case 'cross_field': {
        if (!isEmptyValue(val) && rule.dependentFieldId && record && rule.dependentFieldId in record) {
          const depVal = record[rule.dependentFieldId];
          if (!compareCondition(rule.dependentOperator || 'eq', depVal, rule.dependentValue)) {
            issues.push(rule.message || 'Value does not match the related field');
          }
        }
        break;
      }
    }
  }

  return issues;
}

/** Full validation for a field: metadata config rules + layout block rules. */
export function validateFieldIssues(
  field: SailsFieldDefinition,
  val: any,
  rules?: FieldValidation[],
  record?: Record<string, any>
): string[] {
  const issues = validateFieldValue(field, val);
  const isAutoNumber = (field.logicalType || '').toLowerCase() === 'auto_number';
  issues.push(...evaluateBlockRules(rules, val, record, isAutoNumber));
  return issues;
}

interface DetailFieldInputProps {
  field: SailsFieldDefinition;
  fieldKey: string;
  label: string;
  val: any;
  controlPluginId?: string;
  inert?: boolean; // designer mode: no onChange + pointer-events blocked
  readOnly?: boolean; // system/locked fields: rendered as a control but not editable
  rules?: FieldValidation[]; // block-level rules from the layout config
  showErrors?: boolean; // touched / save-attempted / preview
  record?: Record<string, any>; // sibling values (cross_field rules)
  onChange: (key: string, value: any) => void;
}

export const DetailFieldInput: React.FC<DetailFieldInputProps> = ({
  field, fieldKey, label, val, controlPluginId, inert, readOnly = false, rules, showErrors, record, onChange,
}) => {
  const { controlPlugin } = resolveControlPlugin(field, controlPluginId);
  const issues = validateFieldIssues(field, val, rules, record);
  const showError = !!showErrors && !inert && !readOnly && issues.length > 0;

  const inner = controlPlugin && controlPlugin.RenderEdit ? (
    <ControlLazyBoundary>
      <controlPlugin.RenderEdit
        field={field}
        value={inert ? undefined : val}
        onChange={inert ? undefined : (v) => onChange(fieldKey, v)}
        readOnly={readOnly}
      />
    </ControlLazyBoundary>
  ) : (
    <input
      type="text"
      className="sails-detail-field-input"
      value={inert ? '' : (val ?? '')}
      readOnly={inert || readOnly}
      onChange={(e) => onChange(fieldKey, e.target.value)}
      placeholder={`Enter ${label.toLowerCase()}...`}
    />
  );

  return (
    <div
      className={`ls-block__input-wrapper${showError ? ' is-error' : ''}`}
      style={{ marginTop: 6, ...(inert ? { pointerEvents: 'none' as const } : null) }}
    >
      {inner}
      {showError && (
        <div className="sails-field-error">
          {issues.map((m, i) => (
            <div key={i}>{m}</div>
          ))}
        </div>
      )}
    </div>
  );
};

// ── Read-only / display value (exact front-end fallbacks) ──────

interface DetailFieldDisplayProps {
  field: SailsFieldDefinition;
  val: any;
  controlPluginId?: string;
}

export const DetailFieldDisplay: React.FC<DetailFieldDisplayProps> = ({ field, val, controlPluginId }) => {
  const { controlPlugin, logicalType } = resolveControlPlugin(field, controlPluginId);

  if (val === undefined || val === null || val === '') {
    return <span className="ls-block__empty">—</span>;
  }

  if (controlPlugin && controlPlugin.RenderDisplay) {
    return <controlPlugin.RenderDisplay field={field} value={val} mode="display" />;
  }

  if (logicalType === 'boolean') {
    const cfg = (field.config as any) || {};
    const isTrue = val === true || val === 'true' || val === 1 || val === '1';
    return <span>{isTrue ? (cfg.trueLabel || 'Yes') : (cfg.falseLabel || 'No')}</span>;
  }

  return <span>{typeof val === 'object' ? JSON.stringify(val) : String(val)}</span>;
};
