import { NextRequest, NextResponse } from 'next/server';
import { pool } from '@/lib/knex';
import { QueryLayer, FilterGroupRule } from '@/core/engine/QueryLayer';
import { preprocessFilterGroups } from '@/core/engine/filterPreprocess';
import { resolveTable } from '@/lib/dynamicTable';
import format from 'pg-format';
import { requireSession } from '@/lib/auth/session';
import { validateRecord, sanitizeWritePayload } from '@sails/shared';

type RouteContext = { params: { tableName: string } };

// ---------------------------------------------------------------------------
// POST /api/dynamic/[tableName] — Create a record
// ---------------------------------------------------------------------------
export async function POST(req: NextRequest, { params }: RouteContext) {
  try {
    const { tableName } = params;
    const rawData = await req.json();

    const resolved = await resolveTable(tableName);
    if (!resolved) {
      return NextResponse.json({ error: 'Table not found or access denied.' }, { status: 404 });
    }

    const data = sanitizeWritePayload(resolved.table.fields, rawData);

    // Server-side validation (metadata config: isRequired, min/max, maxLength).
    // Empty payloads are allowed — a blank record is a valid draft, and
    // auto-number fields are generated by column DEFAULTs on insert.
    const issues = validateRecord(resolved.table.fields, data);
    if (issues.length > 0) {
      return NextResponse.json({ error: 'Validation failed', issues }, { status: 422 });
    }

    // QueryLayer handles: AccessGuard (RBAC) → TransactionContext (RLS) → Audit Log
    const newRecord = await QueryLayer.insertRecord(
      pool,
      resolved.schemaName,
      tableName,
      data
    );

    return NextResponse.json(newRecord, { status: 201 });
  } catch (error: any) {
    const status = error.message?.startsWith('Unauthorized') || error.message?.startsWith('Forbidden') ? 403 : 500;
    return NextResponse.json({ error: error.message || 'Failed to insert record.' }, { status });
  }
}

// ---------------------------------------------------------------------------
// GET /api/dynamic/[tableName] — List records with server-side filter/sort/page
//
// Query parameters:
//   ?search=text        — ILIKE across text/varchar fields
//   ?filters=<json>     — {"status":"active","name:contains":"john","age:gt":"18"}
//   ?sort=<json>        — [{"fieldId":"name","dir":"asc"}]
//   ?page=1&limit=25    — pagination (default 1, 25; max 100)
//   ?id=<recordId>      — single-record lookup (detail page)
//   ?ids=c1,c2,c3       — batch lookup of specific records (chip label resolution)
//
// Every field name is validated against tableDefinition.fields before use.
// Both SELECT and COUNT run inside executeSecureQuery for RLS enforcement.
// ---------------------------------------------------------------------------
export async function GET(req: NextRequest, { params }: RouteContext) {
  try {
    const { tableName } = params;
    const { searchParams } = req.nextUrl;

    const resolved = await resolveTable(tableName);
    if (!resolved) {
      return NextResponse.json({ error: 'Table not found or access denied.' }, { status: 404 });
    }

    const recordId = searchParams.get('id');
    const idsRaw = searchParams.get('ids');

    if (idsRaw) {
      const tableMeta = resolved.table;
      const ids = idsRaw.split(',').map(s => s.trim()).filter(Boolean);

      const rows = await QueryLayer.executeSecureQuery(
        pool,
        tableName,
        'read',
        async (client) => {
          if (ids.length === 0) return [];
          // Parameterized ANY($1::text[]) — pg-format %L renders single-element
          // arrays without braces, producing "malformed array literal".
          const sql = format(
            'SELECT * FROM %I.%I WHERE id = ANY($1::text[])',
            resolved.schemaName,
            tableName
          );
          const result = await client.query(sql, [ids]);
          return result.rows;
        }
      );

      return NextResponse.json(
        { rows, total: rows.length, page: 1, limit: ids.length, totalPages: 1, fields: tableMeta?.fields || [] },
        { status: 200 }
      );
    }

    if (recordId) {
      const tableMeta = resolved.table;

      const rows = await QueryLayer.executeSecureQuery(
        pool,
        tableName,
        'read',
        async (client) => {
          const sql = format(
            'SELECT * FROM %I.%I WHERE id = %L',
            resolved.schemaName,
            tableName,
            recordId
          );
          const result = await client.query(sql);
          return result.rows;
        }
      );

      return NextResponse.json(
        { rows, total: rows.length, page: 1, limit: 1, totalPages: 1, fields: tableMeta?.fields || [] },
        { status: 200 }
      );
    }

    const tableMeta = resolved.table;

    const validFields = new Set<string>(
      (tableMeta?.fields || []).map((f: any) => f.fieldName)
    );

    const textTypes = new Set(['text', 'varchar', 'string', 'char', 'email', 'phone', 'url', 'description']);
    const textFields = (tableMeta?.fields || [])
      .filter((f: any) => textTypes.has(f.type?.toLowerCase() || ''))
      .map((f: any) => f.fieldName);

    const jsonbFields = new Set<string>(
      (tableMeta?.fields || [])
        .filter((f: any) => (f.physicalType || '').toLowerCase() === 'jsonb')
        .map((f: any) => f.fieldName)
    );

    const filtersRaw = searchParams.get('filters');
    const filterGroupsRaw = searchParams.get('filterGroups');
    const sortRaw = searchParams.get('sort');

    let filters: Record<string, string> | undefined;
    let filterGroups: { groupLogic: 'and' | 'or'; rules: FilterGroupRule[] }[] | undefined;
    let sort: { fieldId: string; dir: 'asc' | 'desc' }[] | undefined;

    if (filtersRaw) {
      try { filters = JSON.parse(filtersRaw); } catch { /* ignore malformed JSON */ }
    }
    if (filterGroupsRaw) {
      try {
        const parsed = JSON.parse(filterGroupsRaw);
        if (Array.isArray(parsed)) filterGroups = parsed;
      } catch { /* ignore malformed JSON */ }
    }
    if (sortRaw) {
      try {
        const parsed = JSON.parse(sortRaw);
        if (Array.isArray(parsed)) sort = parsed;
      } catch { /* ignore malformed JSON */ }
    }

    // Preprocess grouped filters:
    //  - validate LHS/refField columns against the model's fields
    //  - resolve LHS/RHS drill chains into per-hop table names
    //  - resolve context macros (@me, @today, ...) using the session
    //  - resolve record-source subquery table from the relation field config
    if (filterGroups && filterGroups.length > 0) {
      const session = await requireSession();
      await preprocessFilterGroups({
        session,
        tableName,
        tableFields: (tableMeta?.fields || []) as any[],
        filterGroups,
      });
    }

    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '25');

    const result = await QueryLayer.listRecords(pool, resolved.schemaName, tableName, {
      filters,
      filterGroups,
      search: searchParams.get('search') || undefined,
      sort,
      page: isNaN(page) ? 1 : page,
      limit: isNaN(limit) ? 25 : limit,
      validFields,
      textFields,
      jsonbFields,
    });

    return NextResponse.json(
      { ...result, fields: tableMeta?.fields || [] },
      { status: 200 }
    );
  } catch (error: any) {
    const status = error.message?.startsWith('Unauthorized') || error.message?.startsWith('Forbidden') ? 403 : 500;
    return NextResponse.json({ error: error.message || 'Failed to fetch records.' }, { status });
  }
}

// ---------------------------------------------------------------------------
// PATCH /api/dynamic/[tableName]?id=<recordId> — Update a record
// ---------------------------------------------------------------------------
export async function PATCH(req: NextRequest, { params }: RouteContext) {
  try {
    const { tableName } = params;
    const recordId = req.nextUrl.searchParams.get('id');
    const rawData = await req.json();

    if (!recordId) {
      return NextResponse.json({ error: 'Missing required query param: id.' }, { status: 400 });
    }

    const resolved = await resolveTable(tableName);
    if (!resolved) {
      return NextResponse.json({ error: 'Table not found or access denied.' }, { status: 404 });
    }

    const data = sanitizeWritePayload(resolved.table.fields, rawData);

    // Server-side validation for partial updates — only fields present in the body.
    const patchFields = (resolved.table.fields || []).filter((f: any) =>
      Object.prototype.hasOwnProperty.call(data, f.fieldName)
    );
    const issues = validateRecord(patchFields, data);
    if (issues.length > 0) {
      return NextResponse.json({ error: 'Validation failed', issues }, { status: 422 });
    }

    const updatedRecord = await QueryLayer.updateRecord(
      pool,
      resolved.schemaName,
      tableName,
      recordId,
      data
    );

    return NextResponse.json(updatedRecord, { status: 200 });
  } catch (error: any) {
    const status = error.message?.startsWith('Unauthorized') || error.message?.startsWith('Forbidden') ? 403 : 500;
    return NextResponse.json({ error: error.message || 'Failed to update record.' }, { status });
  }
}

// ---------------------------------------------------------------------------
// DELETE /api/dynamic/[tableName]?id=<recordId> — Delete a record
// ---------------------------------------------------------------------------
export async function DELETE(req: NextRequest, { params }: RouteContext) {
  try {
    const { tableName } = params;
    const recordId = req.nextUrl.searchParams.get('id');

    if (!recordId) {
      return NextResponse.json({ error: 'Missing required query param: id.' }, { status: 400 });
    }

    const resolved = await resolveTable(tableName);
    if (!resolved) {
      return NextResponse.json({ error: 'Table not found or access denied.' }, { status: 404 });
    }

    await QueryLayer.deleteRecord(
      pool,
      resolved.schemaName,
      tableName,
      recordId
    );

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error: any) {
    const status = error.message?.startsWith('Unauthorized') || error.message?.startsWith('Forbidden') ? 403 : 500;
    return NextResponse.json({ error: error.message || 'Failed to delete record.' }, { status });
  }
}

