services:
  inidos-console:
    container_name: inidos-console
    image: inidos-console:latest
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
