/**
 * SAILS Field Validation — single source of truth for client + server.
 * Used by:
 *   - Console (DynamicDetailPage, Layout Studio preview) via DetailFieldInput
 *   - Core API (POST/PATCH /api/dynamic/[tableName]) before write
 *
 * Enforces field-level rules from metadata config:
 *   - isRequired
 *   - min / max  (numeric types: number, decimal, currency, percentage, auto_number)
 *   - maxLength  (text types: short_text, text, email, phone, url, long_text, textarea, rich_text)
 *   - decimalPlaces (decimal, currency, percentage — precision limited to the
 *     configured number of decimal digits; default per type when unset)
 */

import { resolveDecimalPlaces } from './numbers';

export interface ValidationIssue {
  fieldName: string;
  message: string;
}

export interface ValidatableField {
  fieldName?: string;
  logicalType: string;
  isRequired?: boolean;
  /** JSON-compatible metadata config (Prisma JsonValue on the server). */
  config?: any;
  physicalType?: string;
}

const NUMERIC_TYPES = new Set([
  'number',
  'decimal',
  'currency',
  'percentage',
  'percent',
  'auto_number',
]);

const TEXT_TYPES = new Set([
  'short_text',
  'text',
  'email',
  'phone',
  'url',
  'long_text',
  'textarea',
  'rich_text',
]);

export const PRESET_REGEX_MAP: Record<string, { pattern: string; message: string }> = {
  alphanumeric: {
    pattern: '^[a-zA-Z0-9]+$',
    message: 'Only alphanumeric characters allowed (no spaces)',
  },
  alphanumeric_spaces: {
    pattern: '^[a-zA-Z0-9\\s\\-]+$',
    message: 'Only alphanumeric characters, spaces, and dashes allowed',
  },
  alphabetic: {
    pattern: '^[a-zA-Z]+$',
    message: 'Only alphabetic letters allowed',
  },
  alphabetic_spaces: {
    pattern: '^[a-zA-Z\\s]+$',
    message: 'Only alphabetic letters and spaces allowed',
  },
  numeric: {
    pattern: '^[0-9]+$',
    message: 'Only numbers allowed',
  },
  no_special: {
    pattern: '^[a-zA-Z0-9\\s.,\\-_]+$',
    message: 'No special characters allowed',
  },
  url: {
    pattern: '^(https?:\\/\\/)?([a-zA-Z0-9\\-]+\\.)+[a-zA-Z0-9\\-]+.*$',
    message: 'Invalid URL format',
  },
  email: {
    pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
    message: 'Invalid email address format',
  },
};

function toNumber(value: any): number | null {
  if (typeof value === 'number') return Number.isNaN(value) ? null : value;
  if (typeof value === 'string' && value.trim() !== '') {
    const n = Number(value);
    return Number.isNaN(n) ? null : n;
  }
  return null;
}

export function isEmptyValue(value: any): boolean {
  return (
    value === undefined ||
    value === null ||
    value === '' ||
    (Array.isArray(value) && value.length === 0)
  );
}

/** Validate a single field value against its metadata config. Returns error messages. */
export function validateFieldValue(
  field: ValidatableField,
  value: any
): string[] {
  const issues: string[] = [];
  const config = (field.config || {}) as Record<string, any>;

  // Auto-number values are generated by the DB on insert — an empty value is
  // always replaced, so the required gate must not block blank creates.
  const isAutoNumber = (field.logicalType || '').toLowerCase() === 'auto_number';

  // Expression (computed) values are generated server-side on save — never
  // accepted from the client, so the required gate must not block creates.
  const isComputed = (field.logicalType || '').toLowerCase() === 'expression';

  if (field.isRequired && isEmptyValue(value) && !isAutoNumber && !isComputed) {
    issues.push('This field is required');
  }

  if (isEmptyValue(value)) return issues;

  if (NUMERIC_TYPES.has(field.logicalType)) {
    const num = toNumber(value);
    if (num !== null) {
      const min = Number(config.min);
      const max = Number(config.max);
      if (config.min !== undefined && config.min !== null && !Number.isNaN(min) && num < min) {
        issues.push(`Must be at least ${config.min}`);
      }
      if (config.max !== undefined && config.max !== null && !Number.isNaN(max) && num > max) {
        issues.push(`Must be at most ${config.max}`);
      }

      // Precision check: value must not exceed the configured decimal places.
      // Applies to decimal/currency/percentage (defaults per type in numbers.ts).
      // Trailing zeros ("42.5000" with decimalPlaces=2) pass — only true
      // precision is judged. Float-safe via the scaled-integer comparison.
      if (field.logicalType === 'decimal' || field.logicalType === 'currency' || field.logicalType === 'percentage' || field.logicalType === 'percent') {
        const dp = resolveDecimalPlaces(config, field.logicalType);
        if (dp >= 0) {
          const scaled = num * 10 ** dp;
          if (Math.abs(scaled - Math.round(scaled)) > 1e-9) {
            issues.push(`Maximum ${dp} decimal places allowed`);
          }
        }
      }
    }
  }

  if (TEXT_TYPES.has(field.logicalType)) {
    const len = typeof value === 'string' ? value.length : String(value ?? '').length;
    const maxLen = Number(config.maxLength);
    if (config.maxLength !== undefined && config.maxLength !== null && !Number.isNaN(maxLen) && len > maxLen) {
      issues.push(`Max ${config.maxLength} characters`);
    }

    // Regex text format validation (Presets or Custom)
    const preset = config.validationPreset || 'none';
    let patternStr: string | null = null;
    let defaultMsg = 'Invalid format';

    if (preset === 'custom' && config.regexPattern) {
      patternStr = config.regexPattern;
      defaultMsg = 'Format does not match required pattern';
    } else if (PRESET_REGEX_MAP[preset]) {
      patternStr = PRESET_REGEX_MAP[preset].pattern;
      defaultMsg = PRESET_REGEX_MAP[preset].message;
    }

    if (patternStr) {
      try {
        const regex = new RegExp(patternStr);
        const strVal = typeof value === 'string' ? value : String(value ?? '');
        if (!regex.test(strVal)) {
          issues.push(config.customErrorMessage || defaultMsg);
        }
      } catch (err) {
        // Safe fallback for malformed custom regex strings
        issues.push('Invalid validation regex pattern');
      }
    }
  }

  // Email format check — always enforced for email-typed fields. When
  // allowMultiple is on, every comma/semicolon-separated address is validated.
  if (field.logicalType === 'email') {
    const rawStr = typeof value === 'string' ? value : String(value ?? '');
    const addresses = config.allowMultiple
      ? rawStr.split(/[,;]/).map((s: string) => s.trim()).filter(Boolean)
      : [rawStr.trim()];
    const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    for (const addr of addresses) {
      if (!EMAIL_REGEX.test(addr)) {
        issues.push(config.allowMultiple ? `"${addr}" is not a valid email address` : 'Invalid email address');
      }
    }
  }

  return issues;
}

/** Validate all fields against a record of values. Returns field-scoped issues. */
export function validateRecord(
  fields: ValidatableField[],
  values: Record<string, any>
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  for (const field of fields) {
    if (!field.fieldName) continue;
    for (const message of validateFieldValue(field, values[field.fieldName])) {
      issues.push({ fieldName: field.fieldName, message });
    }
  }
  return issues;
}

/** Convert empty-string payload values to null so every blank field stores "no value". */
export function sanitizeWritePayload(
  fields: ValidatableField[],
  payload: Record<string, any>
): Record<string, any> {
  const out = { ...payload };
  for (const field of fields) {
    const key = field.fieldName;
    if (!key || !Object.prototype.hasOwnProperty.call(out, key)) continue;
    // Expression (computed) values are always generated server-side on save.
    // Drop any client-supplied value — computed fields are read-only.
    if ((field.logicalType || '').toLowerCase() === 'expression') {
      delete out[key];
      continue;
    }
    const val = out[key];
    if (typeof val !== 'string' || val.trim() !== '') continue;
    const lt = (field.logicalType || '').toLowerCase();
    // Auto-number values are generated by a PostgreSQL column DEFAULT that fires
    // only when the column is OMITTED from the INSERT. Drop empty values entirely
    // (not null) so create generates the next value and edit preserves the stored
    // one — the sequence is never executed on update.
    if (lt === 'auto_number') {
      delete out[key];
      continue;
    }
    // Expression (computed) values are always generated server-side on save.
    // Drop any client-supplied value — computed fields are read-only.
    if (lt === 'expression') {
      delete out[key];
      continue;
    }
    // All other field types (text, relation/lookup FK, typed, jsonb, select,
    // user, ...) store NULL for a blank value. A NULL FK is valid and satisfies
    // the foreign-key constraint; required fields are blocked by validateRecord
    // before this ever reaches the database.
    out[key] = null;
  }
  return out;
}
